name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 1 * * 2" # Weekly on Tuesdays at 01:00(GMT)

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: "melodic",
            ROS_REPO: "main",
            CATKIN_LINT: "false",
            OPT_VI: "-vi",
            CATKIN_LINT_ARGS: "--ignore unknown_package"}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}